default_config:
    tts:
      - platform: google_translate
    
    group: !include config/groups.yaml
    automation: !include config/automations.yaml
    script: !include config/scripts.yaml
    scene: !include config/scenes.yaml
    